name: Firebase Continuous Deployment

on:
  push:
    branches: [ master ]


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 20.5.1
      - run: npm ci 
      - name: Build project
        env:
          NODE_OPTIONS: --openssl-legacy-provider
        run: npm run build
      - uses: w9jds/firebase-action@v13.4.0
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}