name: Node Continuous Integration

on: 
  pull_request:
    branches: [ master ]


jobs:
  test_pull_request: # job's name
    runs-on: ubuntu-latest # which VM to run on
    steps:
      - uses: actions/checkout@v2 # get source code into the current working directory of the VM
      - uses: actions/setup-node@v1 # run node commands
        with:
          node-version: 20.5.1
      - run: npm ci --verbose # equivalent to npm install, but it does a clean install for your CI server.
      - run: npm test
      - run: npm run build